runner:
  test:
    # Suggestionに対応させるためパッチ可能な diff か rdjson 形式にする必要がある
    # checkstyle形式などは行番号がなくて🐶がコメント先を見失う＆suggestionにならない
    cmd: |-
      echo <<EOL
      --- app/Providers/AppServiceProvider.php
      +++ app/Providers/AppServiceProvider.php
      @@ -12,8 +12,9 @@
           /**
             * Register any application services.
             */
             public function register(): void
             {
                 //
                 // oh
                 // ahhhhhhh
      +
      EOL
    format: diff
